### ISSUE TITLE
Error while creating the edge app on google cloud shell

### ISSUE THREAD

**Issue by salmanfarisvp** [Screenly/cli#220]
Screenly CLI looks ok when running the basic commands. 
```
sfaris@cloudshell:~/Screenly-Playground/edge-apps/countdown-timer$ screenly --version
screenly 0.2.8
```
```
sfaris@cloudshell:~/Screenly-Playground/edge-apps/countdown-timer$ screenly
Usage: screenly [OPTIONS] <COMMAND>

Commands:
  login     Logins with the token and stores it for further use if it's valid. You can set API_TOKEN environment variable to override used API token
  logout    Logouts and removes stored token
  screen    Screen related commands
  asset     Asset related commands
  playlist  Playlist related commands
  edge-app  Edge App related commands
  help      Print this message or the help of the given subcommand(s)

Options:
  -j, --json     Enables JSON output
  -h, --help     Print help (see more with '--help')
  -V, --version  Print version

```

Error is when trying to create an app from template 

```
sfaris@cloudshell:~/Screenly-Playground/edge-apps/countdown-timer$ screenly edge-app create --name countdown-timer --in-place
thread 'main' panicked at src/cli.rs:878:48:
Failed to load authentication.: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Same error when creating a new app

```
sfaris@cloudshell:~/test$ screenly edge-app create --name testAPP 
thread 'main' panicked at src/cli.rs:878:48:
Failed to load authentication.: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
sfaris@cloudshell:~/test$ 
```

**Comment by sergey-borovkov** [comment]
@korvyashka version not updated in Cargo.toml.

>sfaris@cloudshell:~/test$ screenly edge-app create --name testAPP 

can't reproduce. works for me.


>sfaris@cloudshell:~/Screenly-Playground/edge-apps/countdown-timer$ screenly edge-app create --name countdown-timer --in-place

where are you taking new app format tepmplates? It's not going to work with old files.

**Comment by salmanfarisvp** [comment]
> where are you taking new app format tepmplates? It's not going to work with old files.

from here https://github.com/Screenly/Playground/tree/master/edge-apps/countdown-timer

**Comment by sergey-borovkov** [comment]
@salmanfarisvp  it's in the old format still. New cli version has some incompatible changes.

**Comment by salmanfarisvp** [comment]
@sergey-borovkov, but I can't even create a new Edge app. 

```
sfaris@cloudshell:~$ screenly edge-app create --name testApp
thread 'main' panicked at src/cli.rs:823:48:
Failed to load authentication.: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Please note I am running on google cloud shell  - https://shell.cloud.google.com/?show=ide%2Cterminal

**Comment by sergey-borovkov** [comment]
@salmanfarisvp you need to login....
>Failed to load authentication.

**Comment by salmanfarisvp** [comment]
@sergey-borovkov thanks. I didn't log in, and that was the issue.

**Comment by vpetersson** [comment]
@sergey-borovkov we clearly need better error messages.
